#!/usr/bin/env ruby
# frozen_string_literal: true

# Legacy entry point - delegates to `legion lex create`
# Kept for backward compatibility.

$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))

require 'legion/cli'

# Transform: lex_gen create foo -> legion lex create foo
args = ARGV.dup
if args.first == 'create'
  args.shift
  Legion::CLI::Main.start(%w[lex create] + args)
else
  # For subcommands like: lex_gen runner create, actor create etc.
  Legion::CLI::Main.start(['generate'] + args)
end
